services:
  finn-mini:
    build: .
    ports: ["8000:8000"]
    environment:
      - KB_DIR=/app/data/kb
    volumes:
      - ./data:/app/data:ro
      - ./hf_cache:/root/.cache/huggingface
    restart: unless-stopped
