services:
  api:
    build: .
    image: ollama
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./hf_cache:/root/.cache/huggingface   # <-- host-mounted cache
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
